  create table t (name char(5), age int, salary float, primary key(name));
  insert into t values ('aa', 12, 12.5);
  insert into t values ('bb', 34, 100.3);
  select * from t;
  create index index_t_age on t(age) ;
  insert into t values ('cc', 56, 55);
  select * from t;
  select * from t where name = 'aa';
  select * from t where age > 15;
  select * from t where age < 50 and salary > 50;
  delete from t where name = 'aa';
  select * from t;
  delete from t where age > 12;
  select * from t;
  delete from t where age < 50 and salary > 50;
  delete from t;
  insert into t values ('aa', 12, 12.5);
  select * from t;
  drop index index_t_age;
  drop table t;